### ISSUE TITLE
cmstatr and rlang 1.0.0

### ISSUE THREAD

**Issue by lionel-** [cmstatr/cmstatr#27]
Hello,

I'm seeing this problem with dev rlang:

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Snapshot of code has changed:
  old[1:6] vs new[1:6]
    "Code"
    "  res <- basis_normal(x = x, batch = batch)"
  - "Warning <warning>"
  + "Warning <rlang_warning>"
    "  `outliers_within_batch` failed: Maximum normed residual test detected outliers within one or more batch"
    "  `between_batch_variability` failed: Anderson-Darling k-Sample test indicates that batches are drawn from different distributions"
    "  `outliers` failed: Maximum normed residual test detected outliers within data"
```

In general it's not recommended to use `expect_snapshot(cran = TRUE)` because you expose your package to trivial upstream changes, as is the case here. Could you please check that your package is compatible with dev rlang?

We plan to release rlang 1.0.0 in 2 to 4 weeks.

**Comment by kloppen** [comment]
Thanks for the notification, @lionel-

I have addressed this in version [0.9.1](https://github.com/cmstatr/cmstatr/tree/0.9.1) of `cmstatr`. This new version should be on CRAN soon.
